version: '3.2'

services:

  markster-web-staging:
    image: apwells/bottle-tracker-staging
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints: [node.role == manager]
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_public"
        - "traefik.http.routers.markster-web-staging.rule=Host(`bt-staging.alandstreetlab.uk`)"
        - "traefik.http.routers.markster-web-staging.entrypoints=https"
        - "traefik.http.services.markster-web-staging.loadbalancer.server.port=80"
        - "traefik.http.routers.markster-web-staging.tls.certresolver=lets-encrypt"
        - "traefik.http.routers.markster-web-staging.tls=true"
        - "traefik.http.routers.markster-web-staging.tls.domains[0].main=bt-staging.alandstreetlab.uk"
        - "traefik.http.routers.markster-web-staging.tls.domains[0].sans=*.staging.alandstreetlab.uk"
    networks:
      - traefik_public

networks:
  traefik_public:
    external: true
